import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import Link from 'next/Link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>KarlexRose</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <script src='/test.js' strategy='lazyOnload'>

      </script>
      <nav className={styles.mainnav}>
        <ul>
          <Link href="/about"><li>About</li></Link>
          <Link href="/"><li>Home</li></Link>
          <Link href="/blog"><li>Blog</li></Link>
          <Link href="/contact"><li>Contact</li></Link>
        </ul>
      </nav>
      <main className={styles.main}>
        <h1 id='karlex' className={styles.title}>
          Karlex Rose
        </h1>

        <p className={styles.description}>
         The new beginings .
        </p>
        
        <div className="blogs">
          <h2>My Blogs</h2>
          <div className="blogItem1">
            <h3>
              The all new stuff on your finger tips 
            </h3>
            <p>
              The best way to grab the new stuff is to get early access of the new subscription right now .
            </p>
          </div>
        </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
